### ISSUE TITLE
StatusBar Calculation Wrong

### ISSUE THREAD

**Issue by grote** [sjwall/MaterialTapTargetPrompt#14] opened 2016-10-02 20:40 UTC
First of all thanks for this awesome library, I love it! :smile:  :bowing_man: 

The latest version introduced a bug (probably by 91e95397a90b5f8812471bf811a16a48e424d53b). 

![device-2016-10-02-173553](https://cloud.githubusercontent.com/assets/244947/19023550/2960f21e-88c7-11e6-9ecd-2abfbc40f695.png)

This is how it looks with 1.4.0

![device-2016-10-02-173716](https://cloud.githubusercontent.com/assets/244947/19023549/295ff198-88c7-11e6-8a62-17ab2fa68273.png)

**Comment by joseluisametller** [comment] 2016-10-03 08:46
I can reproduce it as well, at least on KitKat. I'm using 1.4.0 for the moment...

**Comment by sjwall** [comment] 2016-10-03 19:35
Hi, thanks letting me know about the issue.

It looks like the issue is occurring due to changes made in d70026e37611f635684e4beb0581b48e68adfd0a, it is incorrectly applying the status bar height when it has already clipped the bounds to the activity.

I hope to have a fix out later today or tomorrow

**Comment by sjwall** [comment] 2016-10-03 20:16
Changes released in v1.4.2, could you please confirm that these changes fix this issue?

**Comment by joseluisametller** [comment] 2016-10-03 21:24
Using 1.4.2 on my gradle file I can still reproduce it on KitKat.

**Comment by sjwall** [comment] 2016-10-04 20:24
The issue is effecting KitKat and lower

**Comment by sjwall** [comment] 2016-10-04 20:54
Issue is the call to `mClipToView.getLocationOnScreen(location);` in `updateClipBounds()`.
It is correctly returning the views screen position from top on KitKat and lower. On Lollipop and newer this returns 0 all the time.

Working on fix for this

**Comment by sjwall** [comment] 2016-10-05 19:30
Should be fixed now. Found different way of retrieving the activity screen location. @joseluisametller and @grote could you both please confirm that this fixes the issue for you. I have tested it with Transportr so I have high hopes

**Comment by joseluisametller** [comment] 2016-10-05 20:53
@sjwall I can confirm it is working perfectly fine on KitKat. Thanks a lot for your work :D

**Comment by sjwall** [comment] 2016-10-07 16:23
@joseluisametller Thanks for confirming. Closing as issue has been fixed

**Closed by sjwall** 2016-10-07 16:23 UTC
Labels: bug
