### ISSUE TITLE
Titles show before animation

### ISSUE THREAD

**Issue by kenumir** [sjwall/MaterialTapTargetPrompt#146] opened 2018-12-11 13:58 UTC
**Describe the bug**
Labels (PrimaryText, SecondaryText) show before animation, hides and show with animation again.

**To Reproduce**
Video https://www.youtube.com/watch?v=8XRp8cZHN9o watch in slow mode ;-)

**Smartphone (please complete the following information):**
 - Device: Nexus 6
 - OS: Android 7.1.1
 - Library version 2.14.0

**Comment by poojagarje** [comment] 2019-03-26 07:34
I'm also facing same issue

**Comment by iljaosintsev** [comment] 2019-08-25 18:06
@sjwall apply [patch](https://github.com/sjwall/MaterialTapTargetPrompt/files/3538449/0001-fix-draw-prompt-text-if-background-has-reached-it.txt) for fix it?

**Comment by sjwall** [comment] 2021-11-01 20:33
@danilodanicomendes yes please do open a PR for it, will be much appriciated

**Comment by sjwall** [comment] 2021-11-06 12:05
The fix for this has been released in v3.3.1

**Closed by sjwall** 2021-11-06 12:05 UTC

**Comment by danilodanicomendes** [comment] 2021-11-06 12:08
Glad to help. Keep up the good work :)

**Comment by peterdk** [comment] 2021-11-06 20:22
I was looking for this bug to fix it, but saw a fix already in place. Nice!
However, I am facing now a weird regression due to upgrade 3.3.0 -> 3.3.1. 
Colors of the text now blend with the background, making my help texts unreadable.
![3 3 0](https://user-images.githubusercontent.com/668007/140622822-6bc3f86e-804d-4231-8d5c-6ac3b2d692de.png)
![3 3 1](https://user-images.githubusercontent.com/668007/140622824-6cbc6525-00ba-4ea3-9af5-8d96ae9b7b5e.png)

Is this due to the Xfer mode? Or is it a other change in the library?
