### ISSUE TITLE
Way to have skip button to skip tutorial

### ISSUE THREAD

**Issue by FaisalFiyyaz** [sjwall/MaterialTapTargetPrompt#165] opened 2019-08-28 00:56 UTC
I have tutorial demo app and I've successfully implemented it for my app but is there a way to have a skip button on the prompt to skip that tutorial?

**Comment by NewestUser** [comment] 2020-01-01 16:14
It will be nice to have a skip button.
I have noticed that a lot of my users end up clicking outside of the prompt.

**Comment by sjwall** [comment] 2020-06-19 15:44
Duplicate of #163

**Closed by sjwall** 2020-06-19 15:44 UTC
